### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by Drzhishi** [AlexZaikin94/MoCo-v2#2]
high,i use quadro p2000(5g) and my computer has 64g memory , I'm sorry it's running main_moco.py for just 10 epoch ,the program ends with an error like cuda out of memory，What modifications should I make to train more epoch。
Similarly, when I run 9epoch and run main_moco.py, the application reports the same error after loading the last training log.
What am I supposed to do?Your opinion will benefit me.

**Comment by Drzhishi** [comment]
I guess there's a problem with the end of the training code because I reported cud out of memory at the end of the three epochs.I really want to use your code to get my  trained Moco model to analysis

**Comment by Drzhishi** [comment]
I guess there's a problem with the end of the training code because I reported cuda out of memory at the end of the three epochs.I really want to use your code to get my trained Moco model to analysis

**Comment by AlexZaikin94** [comment]
> high,i use quadro p2000(5g) and my computer has 64g memory , I'm sorry it's running main_moco.py for just 10 epoch ,the program ends with an error like cuda out of memory，What modifications should I make to train more epoch。 Similarly, when I run 9epoch and run main_moco.py, the application reports the same error after loading the last training log. What am I supposed to do?Your opinion will benefit me.

if you are using my code with the default hyperparams (with a batch size of 32) on a 5GB GPU, the batch size is too large for your GPU
i calibrated the batch size for the hardware i used (1080Ti/2080Ti/Titan Xp), which had 10-11GB of VRAM
if you only have 5GB, i believe decreasing the batch size to 10-16 or using a lighter backbone should solve the issue

**Comment by Drzhishi** [comment]
Thank you for your quick answer, I've reduced the batches size before, but unfortunately I still can't finish training perfectly,may my computer have mistakes. I've finished the useful work in the pre-training phase,and I discovered the pth of the "best" tag that the application automatically saved, and fortunately the model files were exported.I've tried to use them.Thank u so much!!!!!!
